name: Publish Docker Image to Harbor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: docker/login-action@v1
      with:
        registry: ${{ vars.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ vars.HARBOR_REGISTRY }}/${{ vars.HARBOR_REPOSITORY }}/${{ vars.HARBOR_IMAGENAME }}:${{ github.sha }} --tag ${{ vars.HARBOR_REGISTRY }}/${{ vars.HARBOR_REPOSITORY }}/${{ vars.HARBOR_IMAGENAME }}:latest
        docker push -a ${{ vars.HARBOR_REGISTRY }}/${{ vars.HARBOR_REPOSITORY }}/${{ vars.HARBOR_IMAGENAME }}:${{ github.sha }}
